version: '3'

services:
  
    rabbitmq:
        image: rabbitmq:3.7.15-management-alpine
        environment:
            - RABBITMQ_DEFAULT_USER=hellofresh
            - RABBITMQ_DEFAULT_PASS=food
        ports:
            - "5672:5672"
            - "15672:15672"

    product-service:
        image: rodolpheche/wiremock:2.23.2-alpine
        command: --verbose
        volumes:
            - ./wiremock/product-service/stubs:/home/wiremock
        ports:
            - "8081:8080"

    user-service:
        image: rodolpheche/wiremock:2.23.2-alpine
        command: --verbose
        volumes:
            - ./wiremock/user-service/stubs:/home/wiremock
        ports:
            - "8082:8080"

    order-service:
        build: ./order_svc
        command: flask run --host=0.0.0.0 --port=8000
        ports:
            - 8000:8000
        environment:
            - FLASK_APP=app.py
            - FLASK_ENV=production
            - FLASK_DEBUG=1
            - PYTHONUNBUFFERED=1
        depends_on:
            - rabbitmq

